name: docker-build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: docker login
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: build image
        run: docker build -t ${{ secrets.DOCKER_USER }}/url-shortener:${{ github.sha }} .

      - name: push image
        run: docker push ${{ secrets.DOCKER_USER }}/url-shortener:${{ github.sha }}